[package]
name = "skirmish"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peppi = { git = "https://github.com/hohav/peppi.git", version = "1.0.0-alpha.7" }
phf = "0.11.2"
