use std::{
    env, fs,
    path::{Component, Path, PathBuf},
};

#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct AuthoringFile {
    pub(crate) relative: String,
    pub(crate) path: PathBuf,
    pub(crate) source: String,
}

pub(crate) fn generate() {
    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap());
    let repository_root = canonical_directory(
        manifest_dir
            .parent()
            .and_then(Path::parent)
            .expect("script-runtime manifest must live below the repository root"),
        "repository root",
    );
    let source_root = manifest_dir.join("../../scripts/api");
    reject_symlink(&source_root, "authoring API source root");
    let source_root = canonical_directory(&source_root, "authoring API source root");
    assert_within(
        &source_root,
        &repository_root,
        "authoring API source root must remain inside the repository",
    );

    let mut package_roots = Vec::new();
    let entries = fs::read_dir(&source_root).unwrap_or_else(|error| {
        panic!(
            "cannot scan authoring API source root {}: {error}",
            source_root.display()
        )
    });
    for entry in entries {
        let entry = entry.expect("read authoring API source entry");
        let path = entry.path();
        let metadata = checked_metadata(&path, "authoring API source entry");
        if metadata.is_dir() && path.join("__init__.py").is_file() {
            package_roots.push(path);
        }
    }
    package_roots.sort();

    let mut files = Vec::new();
    for package_root in package_roots {
        visit_python_files(&source_root, &package_root, &mut files);
    }
    write_manifest(&source_root, files);
}

fn visit_python_files(source_root: &Path, directory: &Path, files: &mut Vec<AuthoringFile>) {
    let entries = fs::read_dir(directory).unwrap_or_else(|error| {
        panic!(
            "cannot scan authoring API package {}: {error}",
            directory.display()
        )
    });
    for entry in entries {
        let entry = entry.expect("read authoring API package entry");
        let path = entry.path();
        let metadata = checked_metadata(&path, "authoring API package entry");
        if metadata.is_dir() {
            visit_python_files(source_root, &path, files);
        } else if metadata.is_file() && path.extension().is_some_and(|extension| extension == "py")
        {
            let canonical = fs::canonicalize(&path).unwrap_or_else(|error| {
                panic!(
                    "cannot canonicalize authoring API source {}: {error}",
                    path.display()
                )
            });
            assert_within(
                &canonical,
                source_root,
                "authoring API source must remain inside its package root",
            );
            let relative = path
                .strip_prefix(source_root)
                .expect("authoring API path is below source root")
                .components()
                .map(validated_path_component)
                .collect::<Vec<_>>()
                .join("/");
            let source = fs::read_to_string(&path).unwrap_or_else(|error| {
                panic!(
                    "read authoring API source {} as UTF-8: {error}",
                    path.display()
                )
            });
            files.push(AuthoringFile {
                relative,
                path,
                source,
            });
        }
    }
}

fn write_manifest(source_root: &Path, files: Vec<AuthoringFile>) {
    println!("cargo:rerun-if-changed={}", source_root.display());
    for file in &files {
        println!("cargo:rerun-if-changed={}", file.path.display());
    }

    let output = PathBuf::from(env::var_os("OUT_DIR").unwrap()).join("authoring_files.rs");
    fs::write(output, render_manifest(files)).expect("write generated authoring API manifest");
}

pub(crate) fn render_manifest(mut files: Vec<AuthoringFile>) -> String {
    files.sort_by(|left, right| left.relative.cmp(&right.relative));
    let mut generated = "// @generated by crates/script-runtime/build.rs; do not edit.\n"
        .to_owned()
        + "pub(crate) static AUTHORING_FILES: &[(&str, &str)] = &[\n";
    for file in files {
        generated.push_str("    (");
        generated.push_str(&rust_string_literal(&file.relative));
        generated.push_str(", ");
        generated.push_str(&rust_string_literal(&file.source));
        generated.push_str("),\n");
    }
    generated.push_str("];\n");
    generated
}

fn canonical_directory(path: &Path, label: &str) -> PathBuf {
    let path = fs::canonicalize(path)
        .unwrap_or_else(|error| panic!("cannot canonicalize {label} {}: {error}", path.display()));
    assert!(
        path.is_dir(),
        "{label} must be a directory: {}",
        path.display()
    );
    path
}

pub(crate) fn checked_metadata(path: &Path, label: &str) -> fs::Metadata {
    let metadata = fs::symlink_metadata(path)
        .unwrap_or_else(|error| panic!("cannot inspect {label} {}: {error}", path.display()));
    assert!(
        !metadata.file_type().is_symlink(),
        "{label} contains symlink: {}",
        path.display()
    );
    metadata
}

fn reject_symlink(path: &Path, label: &str) {
    let _ = checked_metadata(path, label);
}

pub(crate) fn assert_within(path: &Path, boundary: &Path, message: &str) {
    assert!(
        path.starts_with(boundary),
        "{message}: {} is outside {}",
        path.display(),
        boundary.display()
    );
}

pub(crate) fn validated_path_component(component: Component<'_>) -> String {
    let Component::Normal(component) = component else {
        panic!("authoring API source path contains non-normal component: {component:?}");
    };
    let component = component.to_str().unwrap_or_else(|| {
        panic!("authoring API source path component is not valid UTF-8: {component:?}")
    });
    assert!(
        !component.is_empty()
            && component
                .chars()
                .all(|character| !character.is_control() && character != '\\' && character != '/'),
        "authoring API source path component contains non-printable or unsupported characters: {component:?}"
    );
    component.to_owned()
}

pub(crate) fn rust_string_literal(value: &str) -> String {
    format!("{value:?}")
}
