//! Executable blocked contracts; independent native reference exports are
//! absent. Ignored status is not a passing implementation or fidelity claim.
use serde_json::json;
use sha2::{Digest, Sha256};
use skirmish::game::Controller;
use skirmish_equivalence::{match_trace, trace};
use std::fs;

#[path = "support/reference_scenario.rs"]
mod reference;

#[test]
#[ignore = "blocked: independent native skeleton/bind-parent reference fixture required"]
fn native_skeleton_bind_parents() {
    reference::assert_reference("native_skeleton_bind_parents");
}

#[test]
#[ignore = "blocked: independent non-jab native animation-track reference fixture required"]
fn native_animation_tracks() {
    reference::assert_reference("native_animation_tracks");
}

#[test]
#[ignore = "blocked: independent native hurtbox and bone-attachment reference fixture required"]
fn native_hurtbox_bone_attachments() {
    reference::assert_reference("native_hurtbox_bone_attachments");
}

#[test]
#[ignore = "blocked: independent native ECB bone-attachment reference fixture required"]
fn native_ecb_bone_attachments() {
    reference::assert_reference("native_ecb_bone_attachments");
}

#[test]
#[ignore = "blocked: independent native action-script reference fixture required"]
fn native_action_scripts() {
    reference::assert_reference("native_action_scripts");
}

#[test]
#[ignore = "blocked: independent native stage-topology reference fixture required"]
fn native_stage_topology() {
    reference::assert_reference("native_stage_topology");
}

#[test]
#[ignore = "blocked: independent Nana simulation reference and native support required"]
fn nana_independent_simulation() {
    reference::assert_reference("nana_independent_simulation");
}

#[test]
#[ignore = "blocked: independent original callback-order reference fixture required"]
fn original_callback_order() {
    reference::assert_reference("original_callback_order");
}

#[test]
#[ignore = "blocked: independent native RNG-consumption and checkpoint-restore reference required"]
fn rng_consumption_and_restore() {
    reference::assert_reference("rng_consumption_and_restore");
}

const CASE: &str = "synthetic_loader_regression";

fn synthetic_fixture() -> tempfile::TempDir {
    let directory = tempfile::tempdir().unwrap();
    let data: skirmish::game::data::MatchData =
        serde_json::from_str(include_str!("fixtures/game/integration-match.json")).unwrap();
    let mut inputs = vec![[Controller::default(); 2]; 4];
    inputs[2][0].stick[0] = 0.5;
    let input_bytes = inputs
        .iter()
        .map(|input| serde_json::to_string(input).unwrap() + "\n")
        .collect::<String>()
        .into_bytes();
    let data_bytes = serde_json::to_vec(&data).unwrap();
    let mut expected = Vec::new();
    let mut script = inputs.into_iter();
    // This generated expectation is only a loader regression and is explicitly
    // rejected when the independent-reference entry point is requested.
    match_trace::run(data, 42, |_| Ok(script.next()), &mut expected).unwrap();
    for (name, bytes) in [
        ("data.json", &data_bytes),
        ("inputs.jsonl", &input_bytes),
        ("expected.jsonl", &expected),
    ] {
        fs::write(directory.path().join(name), bytes).unwrap();
    }
    let manifest = json!({
        "schema":1, "case_id":CASE, "seed":42, "restore_before_frame":2,
        "provenance":{
            "kind":"synthetic_loader_test",
            "description":"Wholly synthetic output generated by Skirmish solely to test the loader; no independent fidelity evidence.",
            "source_revision":"0bac93a5ee2f985dac6220bd36ed7078ae6ac0c9",
            "source_sha256":format!("{:x}", Sha256::digest(b"synthetic-loader-regression"))
        },
        "files":{
            "data.json":format!("{:x}", Sha256::digest(&data_bytes)),
            "inputs.jsonl":format!("{:x}", Sha256::digest(&input_bytes)),
            "expected.jsonl":format!("{:x}", Sha256::digest(&expected))
        }
    });
    fs::write(
        directory.path().join("manifest.json"),
        serde_json::to_vec(&manifest).unwrap(),
    )
    .unwrap();
    directory
}

fn verify(directory: &tempfile::TempDir) -> anyhow::Result<trace::Comparison> {
    reference::verify_directory(
        directory.path(),
        CASE,
        reference::ReferenceKind::SyntheticLoaderTest,
    )
}

fn replace_hashed(directory: &tempfile::TempDir, name: &str, bytes: &[u8]) {
    fs::write(directory.path().join(name), bytes).unwrap();
    let path = directory.path().join("manifest.json");
    let mut manifest: serde_json::Value =
        serde_json::from_slice(&fs::read(&path).unwrap()).unwrap();
    manifest["files"][name] = json!(format!("{:x}", Sha256::digest(bytes)));
    fs::write(path, serde_json::to_vec(&manifest).unwrap()).unwrap();
}

#[test]
fn loader_runs_native_physics_and_checkpoint_restore_but_rejects_fake_independence() {
    let directory = synthetic_fixture();
    assert_eq!(verify(&directory).unwrap().frames, 4);
    let error = reference::verify_directory(
        directory.path(),
        CASE,
        reference::ReferenceKind::IndependentNativeReference,
    )
    .unwrap_err();
    assert!(error.to_string().contains("provenance kind"));
}

#[test]
fn loader_detects_a_late_semantic_difference_even_after_hashes_are_updated() {
    let directory = synthetic_fixture();
    let bytes = fs::read(directory.path().join("expected.jsonl")).unwrap();
    let mut records: Vec<serde_json::Value> = std::str::from_utf8(&bytes)
        .unwrap()
        .lines()
        .map(|line| serde_json::from_str(line).unwrap())
        .collect();
    records[3]["state"]["match"]["fighters"][0]["position"][0] = json!("f32:42c80000");
    let altered = records
        .into_iter()
        .map(|record| serde_json::to_string(&record).unwrap() + "\n")
        .collect::<String>();
    replace_hashed(&directory, "expected.jsonl", altered.as_bytes());
    let error = verify(&directory).unwrap_err();
    assert!(error.to_string().contains("frame 2"), "{error:#}");
    assert!(error.to_string().contains("position"), "{error:#}");
}

#[test]
fn loader_rejects_corrupt_hashes_empty_inputs_and_incomplete_reference_traces() {
    for case in 0..3 {
        let directory = synthetic_fixture();
        match case {
            0 => fs::write(directory.path().join("data.json"), b"{}").unwrap(),
            1 => replace_hashed(&directory, "inputs.jsonl", b""),
            _ => {
                let expected = fs::read_to_string(directory.path().join("expected.jsonl")).unwrap();
                let lines: Vec<_> = expected.lines().collect();
                replace_hashed(
                    &directory,
                    "expected.jsonl",
                    (lines[..lines.len() - 1].join("\n") + "\n").as_bytes(),
                );
            }
        }
        let error = verify(&directory).unwrap_err();
        let expected = ["SHA256 mismatch", "nonempty inputs", "missing end"][case];
        assert!(
            error.to_string().contains(expected),
            "case {case}: {error:#}"
        );
    }
}
