/* Independent executable driver: RNG bodies come from the pristine C snapshot
 * includes generated by build.rs and the same documented ABI adapter. */
#include <inttypes.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../oracle/random.c"

/* Match Rust's UTF-8 split_whitespace plus decimal integer parsing. Streaming
 * avoids imposing a token-length limit on otherwise valid leading zeros. */
static int next_character(void) {
    int first = getchar();
    if (first == EOF || first < 0x80) return first;
    if (first < 0xc2 || first > 0xf4) return -2;
    unsigned trailing = first < 0xe0 ? 1 : first < 0xf0 ? 2 : 3;
    uint32_t point = first & (0x3f >> trailing);
    for (unsigned i = 0; i < trailing; ++i) {
        int byte = getchar();
        if (byte < 0x80 || byte > 0xbf) return -2;
        point = (point << 6) | (byte & 0x3f);
    }
    const uint32_t minimum[] = {0, 0x80, 0x800, 0x10000};
    if (point < minimum[trailing] || point > 0x10ffff ||
        (point >= 0xd800 && point <= 0xdfff)) return -2;
    return (int)point;
}

static int whitespace(int point) {
    return (point >= 9 && point <= 13) || point == 0x20 || point == 0x85 ||
        point == 0xa0 || point == 0x1680 || (point >= 0x2000 && point <= 0x200a) ||
        point == 0x2028 || point == 0x2029 || point == 0x202f ||
        point == 0x205f || point == 0x3000;
}

static int integer(int *next, uint32_t maximum, int signed_value, int64_t *result) {
    while (whitespace(*next)) *next = next_character();
    int negative = *next == '-';
    if (negative && !signed_value) return 0;
    if (*next == '+' || negative) *next = next_character();
    if (*next < '0' || *next > '9') return 0;
    uint32_t limit = maximum + negative, value = 0;
    do {
        uint32_t digit = *next - '0';
        if (value > (limit - digit) / 10) return 0;
        value = value * 10 + digit;
        *next = next_character();
    } while (*next >= '0' && *next <= '9');
    if (*next != EOF && !whitespace(*next)) return 0;
    *result = negative ? -(int64_t)value : (int64_t)value;
    return 1;
}

int main(void) {
#ifdef FAIL
    return 7;
#endif
#ifdef HANG
    for (;;) {}
#endif
    int next = next_character();
    int64_t seed_value, frame_value, bound_value;
    if (!integer(&next, UINT32_MAX, 0, &seed_value) ||
        !integer(&next, UINT32_MAX, 0, &frame_value) ||
        !integer(&next, INT32_MAX, 1, &bound_value)) return 2;
    while (whitespace(next)) next = next_character();
    if (next != EOF || ferror(stdin) || frame_value < 1 || frame_value > 1000000) return 2;
    uint32_t input_seed = (uint32_t)seed_value, frames = (uint32_t)frame_value;
    int32_t bound = (int32_t)bound_value;
#ifdef MUTATE_INPUT
    FILE* modified = fopen(getenv("SKIRMISH_TEST_INPUT"), "w");
    if (!modified) return 3;
    fputs("changed", modified);
    fclose(modified);
#endif
    oracle_hsd_set_seed(input_seed);
    oracle_msl_set_seed(input_seed);
    printf("{\"kind\":\"header\",\"schema\":1,\"upstream_commit\":\"0bac93a5ee2f985dac6220bd36ed7078ae6ac0c9\",\"scenario\":\"rng-probe-v1\",\"initial_state\":{\"seed\":%" PRIu32 ",\"frames\":%" PRIu32 ",\"bound\":%" PRId32 "}}\n", input_seed, frames, bound);
    for (uint32_t frame = 0; frame < frames; ++frame) {
        int32_t draw = HSD_Rand();
        float value = HSD_Randf();
        uint32_t bits;
        memcpy(&bits, &value, 4);
        int32_t limited = HSD_Randi(bound);
        int32_t msl = oracle_msl_rand();
#ifdef DIVERGE
        if (frame == 37) draw ^= 1;
#endif
        printf("{\"kind\":\"frame\",\"frame\":%" PRIu32 ",\"inputs\":{\"bound\":%" PRId32 "},\"state\":{\"hsd.rand\":%" PRId32 ",\"hsd.randf\":\"f32:%08" PRIx32 "\",\"hsd.randi\":%" PRId32 ",\"hsd.seed\":%" PRIu32 ",\"msl.rand\":%" PRId32 ",\"msl.seed\":%" PRIu32 "},\"events\":[]}\n", frame, bound, draw, bits, limited, oracle_hsd_get_seed(), msl, oracle_msl_get_seed());
    }
    printf("{\"kind\":\"end\",\"frames\":%" PRIu32 "}\n", frames);
    return 0;
}
