"""Canonical engine action names shared by the authoring descriptors."""

from enum import Enum


class Action(str, Enum):
    WAIT = "wait"
    FALL = "fall"
    JUMP_SQUAT = "jump_squat"
    SPECIAL_N_START = "special_n_start"
    SPECIAL_N_LOOP = "special_n_loop"
    SPECIAL_N_END = "special_n_end"
    SPECIAL_AIR_N_START = "special_air_n_start"
    SPECIAL_AIR_N_LOOP = "special_air_n_loop"
    SPECIAL_AIR_N_END = "special_air_n_end"
    SPECIAL_S = "special_s"
    SPECIAL_S_START = "special_s_start"
    SPECIAL_S_END = "special_s_end"
    SPECIAL_AIR_S = "special_air_s"
    SPECIAL_AIR_S_START = "special_air_s_start"
    SPECIAL_AIR_S_END = "special_air_s_end"
    SPECIAL_HI = "special_hi"
    SPECIAL_AIR_HI = "special_air_hi"
    SPECIAL_HI_HOLD = "special_hi_hold"
    SPECIAL_HI_HOLD_AIR = "special_hi_hold_air"
    SPECIAL_HI_FALL = "special_hi_fall"
    SPECIAL_HI_LANDING = "special_hi_landing"
    SPECIAL_HI_BOUND = "special_hi_bound"
    SPECIAL_LW = "special_lw"
    SPECIAL_LW_START = "special_lw_start"
    SPECIAL_LW_END = "special_lw_end"
    SPECIAL_LW_TURN = "special_lw_turn"
    SPECIAL_LW_HIT = "special_lw_hit"
    SPECIAL_AIR_LW = "special_air_lw"
    SPECIAL_AIR_LW_START = "special_air_lw_start"
    SPECIAL_AIR_LW_END = "special_air_lw_end"
    SPECIAL_AIR_LW_TURN = "special_air_lw_turn"
    SPECIAL_AIR_LW_HIT = "special_air_lw_hit"

    ATTACK_AIR_N = "attack_air_n"
    ATTACK_AIR_F = "attack_air_f"
    ATTACK_AIR_B = "attack_air_b"
    ATTACK_AIR_HI = "attack_air_hi"
    ATTACK_AIR_LW = "attack_air_lw"
    JAB = "jab"
    ATTACK_100_LOOP = "attack100_loop"
    ATTACK_DASH = "attack_dash"
    ATTACK_S3_S = "attack_s3_s"
    ATTACK_HI3 = "attack_hi3"
    ATTACK_LW3 = "attack_lw3"
    ATTACK_S4_S = "attack_s4_s"
    ATTACK_HI4 = "attack_hi4"
    ATTACK_LW4 = "attack_lw4"
    CATCH = "catch"
    CATCH_DASH = "catch_dash"
    CATCH_ATTACK = "catch_attack"
    THROW_F = "throw_f"
    THROW_B = "throw_b"
    THROW_HI = "throw_hi"
    THROW_LW = "throw_lw"
    GUARD = "guard"
    ESCAPE_N = "escape_n"
    ESCAPE_F = "escape_f"
    ESCAPE_B = "escape_b"
    ESCAPE_AIR = "escape_air"
    CLIFF_WAIT = "cliff_wait"
    CLIFF_CLIMB = "cliff_climb"
    CLIFF_ESCAPE = "cliff_escape"
    CLIFF_ATTACK = "cliff_attack"
    CLIFF_JUMP = "cliff_jump"
    DOWN_STAND = "down_stand"
    DOWN_FORWARD = "down_forward"
    DOWN_BACK = "down_back"
    DOWN_ATTACK = "down_attack"
    APPEAL_SR = "appeal_sr"


__all__ = ["Action"]
